# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""
Config-secret cipher tests (task P0-4).

Verifies the versioned-ciphertext implementation with legacy plaintext
pass-through, key-file auto-generation, and fail-fast on key mismatch.
"""

import pytest

from common.util import cipher_util


@pytest.fixture(autouse=True)
def isolate_key(monkeypatch, tmp_path):
    """Each test gets its own key file; the module-level Fernet is reset."""
    key_file = tmp_path / "cipher.key"
    monkeypatch.setenv("REGISTRY_CIPHER_KEY_FILE", str(key_file))
    monkeypatch.delenv("REGISTRY_CIPHER_KEY", raising=False)
    monkeypatch.setattr(cipher_util, "_fernet", None)
    return key_file


class TestRoundTrip:
    def test_encrypt_produces_versioned_prefix(self):
        ct = cipher_util.encrypt("s3cret")
        assert ct.startswith("enc:v1:")
        assert "s3cret" not in ct

    def test_round_trip(self):
        assert cipher_util.decrypt(cipher_util.encrypt("s3cret")) == b"s3cret"

    def test_unicode_round_trip(self):
        assert cipher_util.decrypt(cipher_util.encrypt("密钥-π")) == "密钥-π".encode("utf-8")

    def test_empty_string_passthrough(self):
        assert cipher_util.encrypt("") == ""
        assert cipher_util.decrypt("") == b""


class TestLegacyCompat:
    def test_plaintext_passthrough(self):
        """Pre-existing plaintext conf values decrypt unchanged."""
        assert cipher_util.decrypt("openA2A_T") == b"openA2A_T"

    def test_plaintext_without_prefix_is_not_mangled(self):
        assert cipher_util.decrypt("any legacy value 123") == b"any legacy value 123"


class TestKeyHandling:
    def test_key_file_autogenerated_and_reused(self, isolate_key):
        first = cipher_util.decrypt(cipher_util.encrypt("v1"))
        assert isolate_key.exists()
        key_content = isolate_key.read_text(encoding="utf-8").strip()
        # second call reuses the persisted key
        assert cipher_util.decrypt(cipher_util.encrypt("v2")) == b"v2"
        assert isolate_key.read_text(encoding="utf-8").strip() == key_content

    def test_env_key_takes_precedence(self, isolate_key, monkeypatch):
        monkeypatch.setenv("REGISTRY_CIPHER_KEY", cipher_util._load_or_create_key().decode())
        ct = cipher_util.encrypt("with-env-key")
        assert cipher_util.decrypt(ct) == b"with-env-key"

    def test_wrong_key_fails_fast(self, isolate_key):
        from cryptography.fernet import Fernet as _F
        ct = cipher_util.encrypt("value")  # encrypted with the original key
        # rotate the key: the old ciphertext must fail loudly
        isolate_key.write_text(_F.generate_key().decode(), encoding="utf-8")
        cipher_util._fernet = None
        with pytest.raises(ValueError, match="cipher key does not match"):
            cipher_util.decrypt(ct)

    def test_malformed_key_file_fails_with_clear_message(self, isolate_key):
        isolate_key.write_text("not-valid-fernet-key-material", encoding="utf-8")
        cipher_util._fernet = None
        with pytest.raises(ValueError, match="not valid Fernet key material"):
            cipher_util.encrypt("value")

    def test_corrupted_ciphertext_fails_fast(self, isolate_key):
        ct = cipher_util.encrypt("value")[len("enc:v1:"):]
        corrupted = "enc:v1:" + ct[:-4] + "AAAA"
        with pytest.raises(ValueError, match="cipher key does not match"):
            cipher_util.decrypt(corrupted)
